version: "3"

services:
  app:
    container_name: app
    restart: always
    build: .
    environment: 
      - PORT=7000 
    ports: 
      - "7000:7000" 
    links: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    command: mongod --auth
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_volume:/data/db
volumes:
    mongodb_data_volume:
        external: true